import { useEffect, useRef, useState } from 'react'
import mermaid from 'mermaid'

mermaid.initialize({
  startOnLoad: false,
  theme: 'neutral',
  fontFamily: 'var(--font-main)',
})

let idCounter = 0

function MermaidBlock({ chart }) {
  const ref = useRef(null)
  const [svg, setSvg] = useState('')
  const [error, setError] = useState(null)

  useEffect(() => {
    const id = `mermaid-${++idCounter}`
    let cancelled = false

    mermaid.render(id, chart).then(
      ({ svg: rendered }) => {
        if (!cancelled) setSvg(rendered)
      },
      (err) => {
        if (!cancelled) setError(err?.message || 'Failed to render diagram')
      },
    )

    return () => { cancelled = true }
  }, [chart])

  if (error) {
    return <pre className="mermaid-error">{error}</pre>
  }

  // SVG is generated by mermaid.render(), not from user input
  return (
    <div
      ref={ref}
      className="mermaid-diagram"
      dangerouslySetInnerHTML={{ __html: svg }}
    />
  )
}

export default MermaidBlock
